# 1 워크플로의 이름 지정
name: CI

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    # 4 실행스텝지정
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: aws s3 cp --recursive --region ap-northeast-2 dist s3://my-github-actions-bucket-sss
