# 1 워크플로의 이름 지정
name: CI

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    # 4 실행스텝지정
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/ci.yml
